name: app_ditonton
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  get_it: ^7.6.0
  core:
    path: modules/core
  movies:
    path: modules/movies
  about:
    path: modules/about
  search:
    path: modules/search
  watchlist:
    path: modules/watchlist
  tvseries:
    path: modules/tvseries

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3
  sqflite_common_ffi: ^2.2.5

flutter:
  uses-material-design: true