// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlgrG-HU2r9KuGc6rDFSTVe004XXpC1UQ',
    appId: '1:1008604347139:web:ba09b50b5682477b90c736',
    messagingSenderId: '1008604347139',
    projectId: 'ditonton-9de91',
    authDomain: 'ditonton-9de91.firebaseapp.com',
    storageBucket: 'ditonton-9de91.appspot.com',
    measurementId: 'G-HHDX15NGM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRSdyxIhSYsBkTnCUEpaUp4iWnOIHVxA',
    appId: '1:1008604347139:android:f7bcf925a11b2b2790c736',
    messagingSenderId: '1008604347139',
    projectId: 'ditonton-9de91',
    storageBucket: 'ditonton-9de91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQwDmId3hlxuy1r0Zhbah3qRf2RvDY2g',
    appId: '1:1008604347139:ios:a5be8db5d14da1de90c736',
    messagingSenderId: '1008604347139',
    projectId: 'ditonton-9de91',
    storageBucket: 'ditonton-9de91.appspot.com',
    iosClientId: '1008604347139-2hjtd0laluu98ndffgdkkbs70s4b1hqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDitonton',
  );
}
