// Mocks generated by Mockito 5.4.1 from annotations
// in watchlist/test/test_helper/test_helper_watchlist.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i15;

import 'package:core/core.dart' as _i10;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/movies.dart' as _i11;
import 'package:sqflite/sqflite.dart' as _i7;
import 'package:tvseries/tvseries.dart' as _i12;
import 'package:watchlist/data/datasources/db/database_helper.dart' as _i5;
import 'package:watchlist/data/datasources/watchlist_local_data_source.dart'
    as _i13;
import 'package:watchlist/data/models/watchlist_table_model.dart' as _i8;
import 'package:watchlist/domain/repositories/watchlist_repository.dart' as _i9;
import 'package:watchlist/domain/usecases/get_watchlist_movies.dart' as _i3;
import 'package:watchlist/domain/usecases/get_watchlist_tv.dart' as _i4;
import 'package:watchlist/presentation/provider/watchlist_notifier.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistMovies_1 extends _i1.SmartFake
    implements _i3.GetWatchlistMovies {
  _FakeGetWatchlistMovies_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetWatchlistTv_2 extends _i1.SmartFake
    implements _i4.GetWatchlistTv {
  _FakeGetWatchlistTv_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i5.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i7.Database?>.value(),
      ) as _i6.Future<_i7.Database?>);
  @override
  set database(_i6.Future<_i7.Database?>? name) => super.noSuchMethod(
        Invocation.setter(
          #database,
          name,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<int> insertWatchlist(_i8.WatchlistTableModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [data],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<int> removeWatchlist(_i8.WatchlistTableModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [data],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getWatchlistById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistById,
          [id],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlist(
          {required String? typeWatchlist}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlist,
          [],
          {#typeWatchlist: typeWatchlist},
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i9.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i10.Failure, String>> saveWatchlistMovie(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistMovie,
          [movie],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistMovie,
            [movie],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i10.Failure, String>> saveWatchlistTv(
          _i12.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlistTv,
          [tv],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlistTv,
            [tv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i10.Failure, String>> removeWatchlistMovie(
          _i11.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistMovie,
          [movie],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistMovie,
            [movie],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i6.Future<_i2.Either<_i10.Failure, String>> removeWatchlistTv(
          _i12.TvDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTv,
          [tv],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlistTv,
            [tv],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, String>>);
  @override
  _i6.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getWatchlistMovie() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovie,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #getWatchlistMovie,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
  @override
  _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>>.value(
            _FakeEither_0<_i10.Failure, List<_i12.Tv>>(
          this,
          Invocation.method(
            #getWatchlistTv,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>>);
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i13.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertWatchlist(_i8.WatchlistTableModel? watchlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [watchlist],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<String> removeWatchlist(_i8.WatchlistTableModel? watchlist) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [watchlist],
        ),
        returnValue: _i6.Future<String>.value(''),
      ) as _i6.Future<String>);
  @override
  _i6.Future<_i8.WatchlistTableModel?> getWatchlistById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistById,
          [id],
        ),
        returnValue: _i6.Future<_i8.WatchlistTableModel?>.value(),
      ) as _i6.Future<_i8.WatchlistTableModel?>);
  @override
  _i6.Future<List<_i8.WatchlistTableModel>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i6.Future<List<_i8.WatchlistTableModel>>.value(
            <_i8.WatchlistTableModel>[]),
      ) as _i6.Future<List<_i8.WatchlistTableModel>>);
  @override
  _i6.Future<List<_i8.WatchlistTableModel>> getWatchlistTv() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTv,
          [],
        ),
        returnValue: _i6.Future<List<_i8.WatchlistTableModel>>.value(
            <_i8.WatchlistTableModel>[]),
      ) as _i6.Future<List<_i8.WatchlistTableModel>>);
}

/// A class which mocks [WatchlistNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistNotifier extends _i1.Mock implements _i14.WatchlistNotifier {
  MockWatchlistNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetWatchlistMovies get getWatchlistMovies => (super.noSuchMethod(
        Invocation.getter(#getWatchlistMovies),
        returnValue: _FakeGetWatchlistMovies_1(
          this,
          Invocation.getter(#getWatchlistMovies),
        ),
      ) as _i3.GetWatchlistMovies);
  @override
  _i4.GetWatchlistTv get getWatchlistTv => (super.noSuchMethod(
        Invocation.getter(#getWatchlistTv),
        returnValue: _FakeGetWatchlistTv_2(
          this,
          Invocation.getter(#getWatchlistTv),
        ),
      ) as _i4.GetWatchlistTv);
  @override
  List<_i11.Movie> get watchlistMovies => (super.noSuchMethod(
        Invocation.getter(#watchlistMovies),
        returnValue: <_i11.Movie>[],
      ) as List<_i11.Movie>);
  @override
  List<_i12.Tv> get watchlistTv => (super.noSuchMethod(
        Invocation.getter(#watchlistTv),
        returnValue: <_i12.Tv>[],
      ) as List<_i12.Tv>);
  @override
  _i10.RequestState get watchlistState => (super.noSuchMethod(
        Invocation.getter(#watchlistState),
        returnValue: _i10.RequestState.empty,
      ) as _i10.RequestState);
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: '',
      ) as String);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i6.Future<void> fetchWatchlistMovies() => (super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistMovies,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> fetchWatchlistTv() => (super.noSuchMethod(
        Invocation.method(
          #fetchWatchlistTv,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i3.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
}

/// A class which mocks [GetWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTv extends _i1.Mock implements _i4.GetWatchlistTv {
  MockGetWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>>.value(
            _FakeEither_0<_i10.Failure, List<_i12.Tv>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Either<_i10.Failure, List<_i12.Tv>>>);
}
