name: tvseries
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  flutter_bloc: ^8.1.3
  core:
    path: ../core
  watchlist:
    path: ../watchlist

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
  bloc_test: ^9.1.3
  mocktail: ^0.3.0

flutter:
  assets:
    - packages/core/assets_core/no-image.gif
    - packages/core/assets_core/error-data.gif
    - packages/core/assets_core/empty-data.gif
