name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  intl: ^0.18.1
  http: ^0.13.6
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  provider: ^6.0.5
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:

